ENTRIES=\
	Fonts/DroidSans.ttf \
	Locale/en \
	Menu/ButtonBackground.png \
	Player/Player.obj \
	Player/Player.png \
	World/Textures/Grass.png \
	World/Textures/Skybox.png

$(BUILD_DIR)/resources.bin: $(BUILD_DIR)/packer $(ENTRIES)
	$(BUILD_DIR)/packer $@ $(ENTRIES)
